name: Bump Headlamp version

# This action will update the Headlamp version from upstream and create a PR.
on:
  repository_dispatch:
    types:
      - headlamp-release
  workflow_dispatch:

jobs:
  create_pr_to_upgrade_minikube:
    name: Create PR to upgrade minikube
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 19.x
    - name: Setup jq
      run: |
        sudo apt-get install -y jq
    - name: Checkout headlamp repo
      uses: actions/checkout@v2
    - name: Bump to latest Headlamp version
      run: |
        npm i node-fetch@2.6.1
    - name: Configure Git
      run: |
        user=${{github.actor}}
        if [ -z $user ]; then
          user=joaquimrocha
        fi
        git config --global user.name "$user"
        git config --global user.email "$user@users.noreply.github.com"
    - name: Update headlamp version in minikube
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        HEADLAMP_VERSION=$(curl -X GET https://api.github.com/repos/headlamp-k8s/headlamp/releases/latest | jq -r '.tag_name')
        user=$(git config --global user.name)
        git checkout -b "update_headlamp_$HEADLAMP_VERSION"
        node ./update-release.js $HEADLAMP_VERSION
        git diff
        git add -u
        git status
        git commit -m "Update for Headlamp $HEADLAMP_VERSION"
        git status
        git push origin "update_headlamp_$HEADLAMP_VERSION" -f
        gh pr create \
        --title "Update for Headlamp $HEADLAMP_VERSION" \
        --assignee "$user" \
        --body "Update Headlamp version to $HEADLAMP_VERSION
          cc: @$user"
